### ISSUE TITLE
Can not compile with ubuntu and asterisk 1.8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shaman7036/asterisk-chan-dongle#24]
```
What steps will reproduce the problem?
1. configure
2. make

What is the expected output? What do you see instead?

chan_dongle-1.1.r10$ sudo make
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/src/asterisk-1.8.5.0/include 
-I/usr/include -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall -Wextra -MD -MT 
app.o -MF .app.o.d -MP  -o app.o -c app.c
In file included from app.c:17:0:
/usr/src/asterisk-1.8.5.0/include/asterisk.h:21:33: fatal error: 
asterisk/autoconfig.h: No such file or directory
compilation terminated.
make: *** [app.o] Error 1


What version of the product are you using? On what operating system?

ubuntu 11 desktop

asterisk 1.8.5.0

standard kernel: 2.6.38-10-generic

Please provide any additional information below.
Also using SVN and giving command autoconf && automake gives me some error.


```

Original issue reported on code.google.com by `michele....@gmail.com` on 6 Aug 2011 at 10:49

**Comment by GoogleCodeExporter** [comment]
```
your asterisk not configured ?
```

Original comment by `bg_...@mail.ru` on 7 Aug 2011 at 9:01

**Comment by GoogleCodeExporter** [comment]
```
Yes but not compiled :-(

So this afternoon jus to be sure:
1)Installed new Ubuntu server 10.10 LTS on virtualbox
2)Updated everything
3)downloaded asterisk source ,compiled and installed
4)Finally chan- dongle compiled and installed!

I don t know if with ubuntu 11 is the same

Autoconf and automake still not chance to work .

After confured i have issue number 23 :I can call but I don t hear anything 
from other side :-(((

The fact is that with datacard and Openwrt and asterisk 1.6 the same usb key 
works well with bidirectional audio!


```

Original comment by `michele....@gmail.com` on 7 Aug 2011 at 8:38

**Comment by GoogleCodeExporter** [comment]
```
(confured typo error .It's means:after I configured asterisk properly :-)) )

```

Original comment by `michele....@gmail.com` on 7 Aug 2011 at 8:40

**Comment by GoogleCodeExporter** [comment]
```
Try this:
cd dongle_chanwtf
./configure --includedir=/usr/local/src/asterisk/asterisk-1.8.5.0/include/

this helped me to configure it
```

Original comment by `aleksand...@gmail.com` on 6 Oct 2011 at 2:49

**Comment by GoogleCodeExporter** [comment]
```
hi, i found solution, try :
sudo apt-get install asterisk-dev
```

Original comment by `isama...@gmail.com` on 27 Nov 2013 at 4:39
