### ISSUE TITLE
Asterisk 12

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shaman7036/asterisk-chan-dongle#167]
```
There is a version test to asterisk 12?
```

Original issue reported on code.google.com by `jersonju...@gmail.com` on 19 Feb 2014 at 1:18

**Comment by GoogleCodeExporter** [comment]
```
i think 11 and 12 looks same.
use unofficial patch for asterisk 10 and 11

```

Original comment by `bg_...@mail.ru` on 29 Apr 2014 at 7:50
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `bg_...@mail.ru` on 29 Apr 2014 at 7:51
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
root@cubie:/usr/src/asterisk-chan-dongle-asterisk11# make
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include 
-DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall 
-Wextra -MD -MT app.o -MF .app.o.d -MP  -o app.o -c app.c
app.c: In function ‘app_status_exec’:
app.c:37:2: warning: missing initializer [-Wmissing-field-initializers]
app.c:37:2: warning: (near initialization for ‘args.resource’) 
[-Wmissing-field-initializers]
app.c: In function ‘app_send_sms_exec’:
app.c:82:2: warning: missing initializer [-Wmissing-field-initializers]
app.c:82:2: warning: (near initialization for ‘args.device’) 
[-Wmissing-field-initializers]
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include 
-DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall 
-Wextra -MD -MT at_command.o -MF .at_command.o.d -MP  -o at_command.o -c 
at_command.c
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include 
-DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall 
-Wextra -MD -MT at_parse.o -MF .at_parse.o.d -MP  -o at_parse.o -c at_parse.c
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include 
-DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall 
-Wextra -MD -MT at_queue.o -MF .at_queue.o.d -MP  -o at_queue.o -c at_queue.c
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include 
-DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall 
-Wextra -MD -MT at_read.o -MF .at_read.o.d -MP  -o at_read.o -c at_read.c
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include 
-DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall 
-Wextra -MD -MT at_response.o -MF .at_response.o.d -MP  -o at_response.o -c 
at_response.c
gcc -g -O2 -O6 -I.  -D_GNU_SOURCE -I/usr/include -I/usr/include 
-DASTERISK_VERSION_NUM=110000 -DHAVE_CONFIG_H  -fvisibility=hidden -fPIC -Wall 
-Wextra -MD -MT chan_dongle.o -MF .chan_dongle.o.d -MP  -o chan_dongle.o -c 
chan_dongle.c
chan_dongle.c: In function ‘public_state_init’:
chan_dongle.c:1668:11: error: too few arguments to function 
‘ast_format_cap_alloc’
/usr/include/asterisk/format_cap.h:52:24: note: declared here
make: *** [chan_dongle.o] Error 1

```

Original comment by `jersonju...@gmail.com` on 3 May 2014 at 2:34

**Comment by GoogleCodeExporter** [comment]
```
Sory for my bad english.Tel me please how to install this module on asterisk 12
```

Original comment by `781pa...@gmail.com` on 26 May 2014 at 2:37

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Found a solution of the problem?
```

Original comment by `kaprano...@gmail.com` on 9 Oct 2014 at 9:32

**Comment by GoogleCodeExporter** [comment]
```
No solution. Works with asterisk 1.8 and 11!
```

Original comment by `jersonju...@gmail.com` on 9 Oct 2014 at 10:42

**Comment by GoogleCodeExporter** [comment]
```
The same issue for me! Asterisk 12.5
```

Original comment by `vasiliev...@gmail.com` on 27 Oct 2014 at 1:01

**Comment by GoogleCodeExporter** [comment]
```
Works on Aaterisk 1.8 and 11.X. Asterisk 12 and 13 only when developers or some 
kind soul develop a patch for those versions!
```

Original comment by `jersonju...@gmail.com` on 27 Oct 2014 at 1:59

**Comment by GoogleCodeExporter** [comment]
```
he same issue for me! Asterisk 12. Freepbx and Centos
```

Original comment by `wilton.f...@gmail.com` on 5 Nov 2014 at 1:02

**Comment by GoogleCodeExporter** [comment]
```
Works fine with FreePBX 12 and Asterisk 11 version!
```

Original comment by `jersonju...@gmail.com` on 5 Nov 2014 at 1:49

**Comment by GoogleCodeExporter** [comment]
```
jersonju...@gmail.com - chan-dongle does work for Asterisk 11 - it has to be 
compiled into Asterisk source and then compile Asterisk. Look for it on github.
```

Original comment by `borg.jon...@gmail.com` on 3 Mar 2015 at 10:22

**Comment by GoogleCodeExporter** [comment]
```
I know. Do not works with asterisk 13.
```

Original comment by `jersonju...@gmail.com` on 3 Mar 2015 at 10:29

**Comment by GoogleCodeExporter** [comment]
```
I modified it for asterisk 13. https://forum.openwrt.org/viewtopic.php?id=54343

```

Original comment by `petr.opl...@gmail.com` on 31 Mar 2015 at 11:49

**Comment by GoogleCodeExporter** [comment]
```
This versions work with incomming calls. When I do Outgoing calls asterisk 
crash.

https://forum.openwrt.org/viewtopic.php?id=54343
```

Original comment by `jersonju...@gmail.com` on 31 Mar 2015 at 12:09
